### PR TITLE
Update example instructions with front end build commands

### PR DESCRIPTION
**Pull request by gigasquid**
Update the example instructions to include the front end instructions too and update the port

### CODE REVIEW

**Comment by harold** [comment]
Since this uses `think.gate`, you should not have to do anything w/ figwheel or garden yourself (gate should manage these transparently):

Figwheel/js:
https://github.com/thinktopic/think.gate/blob/master/src/clj/think/gate/core.clj#L131

Garden/css:
https://github.com/thinktopic/think.gate/blob/master/src/clj/think/gate/core.clj#L94

I haven't actually used this suite/classifier myself, so maybe I'm missing something.

**Comment by gigasquid** [comment]
@harold cool. I misunderstand feedback from https://groups.google.com/forum/#!topic/clojure-cortex/8NVAX8IEPWA. I just confirmed that it is not needed.  Looks great! 👯

**Comment by cnuernber** [comment]
Thanks for this work, it is really helping.

**Comment by harold** [comment]
@gigasquid - Cool! Thanks for this PR. (:

**Pull request merged**
