### PR TITLE
Fix convolutional dimension checks

### PR DESCRIPTION
**Pull request by maxbendick**
Fix the checks on kernel and stride dimensions for convnets and the error message if they fail.

### CODE REVIEW

**Comment by harold** [comment]
Interesting. Did you encounter negative strides? Maybe we need a test for this.

**Comment by maxbendick** [comment]
Nope, never ran into negative strides in the wild. I saw it while browsing the code, and it looked a little odd to me.

**Comment by harold** [comment]
Cool! Thanks again.

**Comment by harold** [comment]
Closing in favor of a local branch with @maxbendick's commit, and some trivial tests:
https://github.com/thinktopic/cortex/pull/229

**Pull request closed without merging**
