### PR TITLE
SGD with Nesterov Momentum

### PR DESCRIPTION
**Pull request by rosejn**
I've added SGD with Nesterov momentum for both CPU and GPU.  

The mnist training tests are passing so I think it is working OK, but I'm getting a NaN with the corn test.  When I try running the corn test on the repl I get some strange errors though, so I think I'm missing some kind of setup/teardown mechanism that I need to be using in order to run it manually.

Just to try this out I changed the optimizers used in cortex.verify.nn.train to (sgd/sgd) rather than (adam/adam).  Not sure if it's worth testing both every time, or maybe use sgd on one test and adam on another?

### CODE REVIEW

**Comment by cnuernber** [comment]
Sounds like a solid addition.  We need this to ensure we can repeat certain types of experiments; adam is handy but the research is pretty much all using sgd.  Mind if I spend a little time with this to move it to the tensors?  Then it will not need a gpu/cpu implementation.

**Comment by rosejn** [comment]
Yeah totally, go for it.  I just used the Adam optimizer implementations as templates, but if there's a better way with some of the new stuff it would be cool to see how that works.

**Comment by cnuernber** [comment]
If we can be ok with the cost of a temporary variable then I can do it with vector math using the tensor system.  This means no cuda kernel, no cpu kernel, lots of good stuff.  But the cost of a parameter could make the network quite a lot bigger in some cases where the parameter size is fairly large.  There are other ways to mitigate this later which would be to allow optimizers to reuse buffers but this limits the parallelism implied in the optimizer; tradeoffs all around.

**Comment by cnuernber** [comment]
Decided to use a single variable that will grow to the size of the largest parameter buffer.  This should be significantly smaller than another buffer the size of parameters.  (yet again, parameter, gradient, momentum is x3).  The tests passed the first time (in at least networks using this actually train).  So this can go in as soon as travis says so.

**Pull request merged**
