### PR TITLE
[suite-cleanup/ch773] Move css -> example.

### PR DESCRIPTION
**Pull request by harold**
The only consumer of these styles is the example, so just move them there.

(Toward decomposing suite)

### CODE REVIEW

**Comment by cnuernber** [comment]
This is an artifact of the large refactor.  Originally:

https://github.com/thinktopic/cortex/blob/master/examples/suite-classification/cljs/cortex/suite/classify.cljs

This was under the suite project.  This has allowed us to see visualizations of the confusions matrix when we are doing classification outside of suite-classification.

I hadn't noticed this file has moved but now we have effectively removed a major feature and I am not happy about that as we have used the confusion matrix cljs stuff a lot while training other networks.

Now it is not possible for a client of cortex to visualize in the same way without copying a lot of code around.  Although there is an argument for moving all cljs visualization (and thus gate) into it's own subproject so that the base cortex library is tighter.

@charlesg3 @poojaramesh

**Comment by charlesg3** [comment]
I don't think cortex should depend on gate and cljs stuff, but this is a useful feature for debugging ... Let's move it to a subproject

**Comment by cnuernber** [comment]
Agreed about that cljs dependency.  I think making the cljs stuff simple to use (but not a required dependency) dovetails well with @harold's existing work.

**Comment by poojaramesh** [comment]
@charlesg3, @cnuernber Would the cortex-visualization sub-project be a better place for the this and a lot of the supporting confusion matrix code that is currently in suite-classification and examples/suite-classification? 

The mnist example would then serve as a true example of how to use suite-classification and cortex-visualization. There's a lot of great functionality in examples/suite-classification and it might get overlooked if a user does not take the time to scan the code in the namespace.

**Comment by charlesg3** [comment]
Yes I think that is a good place for that code to live. If we end up using it a lot and want to create a library or the like I think creating something called `cortex-contrib` would be nice to have all the bells and whistles while keeping the core more streamlined.

**Comment by cnuernber** [comment]
Agreed Pooja that is a good solution.  Let's plan on that.

**Comment by harold** [comment]
I agree with everything said here.

Pooja had mentioned that she is already using the classification example as a library in her own work, so I was headed toward that. There are a lot of layers of helpers we can build up for users doing classification that don't generalize to every nn; I think having a clear separation will help users know which tools apply to the type of problem they're solving.

**Pull request merged**
