### PR TITLE
cpu-only

### PR DESCRIPTION
**Pull request by charlesg3**
@cnuernber -- This is what I came up with for getting things to compile on the CPU. I verified that it works on my laptop (no nvidia drivers using the cpu-only test selectors) and on my desktop (nvidia drivers, all tests). I think there may be a more clever way to just dynamically load things once, so if anything is in a tight inner loop we might consider that.

### CODE REVIEW

**Comment by cnuernber** [comment]
If it works then it is a definite step forward; I would like to push it in and then worry about a more cohesive design later if we want to worry about that.

**Comment by charlesg3** [comment]
Feel free to push the button. Once this lands we can back-out the testing in a docker container https://github.com/thinktopic/cortex/blob/master/scripts/build-docker-and-test.sh#L3 in favor of simply testing directly on travis, which presumably will speed things up a bit.

**Comment by cnuernber** [comment]
The importers require libhdf5 at a particular version which isn't available for ubuntu versions.  Maybe we could test on a pre-built container?

**Comment by charlesg3** [comment]
Ah, I was forgetting about that dependency. Using a pre-built container could speed things up, but without being able to skip jumping through the docker hoops it isn't _as_ enticing. Then again, that "docker build" could simply be changed to a "docker pull". Let me know if you'd like to go this route and I'd be happy to put the built container on public dockerhub and update the build flow.

**Pull request merged**
